version: '3.8'

services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/yuansai/guisheng:v1
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: p93la3LpWL5G
      DB_USER: postgres
      DB_NAME: postgres
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - 3000:3000
  
  # The postgres database: 
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: p93la3LpWL5G
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - myevershop

  # The Nginx service:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/yuansai/nginx:v1
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - myevershop

networks:
  myevershop:
    driver: bridge

volumes:
  postgres-data:
